# Generated by Django 5.0.1 on 2025-05-21 05:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatbotInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_query", models.TextField()),
                ("ai_response", models.TextField()),
                ("feedback_helpful", models.BooleanField(blank=True, null=True)),
                ("feedback_comment", models.TextField(blank=True)),
                ("context", models.JSONField(blank=True, default=dict)),
                ("session_id", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CourseMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enrollment_count", models.PositiveIntegerField(default=0)),
                ("completion_count", models.PositiveIntegerField(default=0)),
                ("dropout_count", models.PositiveIntegerField(default=0)),
                (
                    "avg_completion_time_days",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "avg_rating",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
                ),
                ("total_review_count", models.PositiveIntegerField(default=0)),
                (
                    "avg_quiz_score",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "engagement_score",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "course metric",
                "verbose_name_plural": "course metrics",
            },
        ),
        migrations.CreateModel(
            name="LearningProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("viewed", models.BooleanField(default=False)),
                ("completed", models.BooleanField(default=False)),
                ("time_spent_seconds", models.PositiveIntegerField(default=0)),
                ("last_position_seconds", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["course", "chapter"],
            },
        ),
        migrations.CreateModel(
            name="RecommendationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recommendation_reason", models.CharField(max_length=255)),
                (
                    "recommendation_score",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("features_used", models.JSONField(default=list)),
                ("was_clicked", models.BooleanField(default=False)),
                ("was_enrolled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("course_view", "Course View"),
                            ("chapter_view", "Chapter View"),
                            ("quiz_start", "Quiz Start"),
                            ("quiz_submit", "Quiz Submit"),
                            ("download", "Download"),
                            ("search", "Search"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("context", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("device_type", models.CharField(blank=True, max_length=20)),
                ("session_id", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "user activity",
                "verbose_name_plural": "user activities",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("courses_enrolled", models.PositiveIntegerField(default=0)),
                ("courses_completed", models.PositiveIntegerField(default=0)),
                (
                    "avg_course_completion_time_days",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("total_learning_time_seconds", models.PositiveIntegerField(default=0)),
                (
                    "avg_quiz_score",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("login_count", models.PositiveIntegerField(default=0)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                (
                    "engagement_score",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "user metric",
                "verbose_name_plural": "user metrics",
            },
        ),
    ]
