# Generated by Django 5.0.1 on 2025-05-21 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("analytics", "0001_initial"),
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatbotinteraction",
            name="chapter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chatbot_interactions",
                to="courses.chapter",
            ),
        ),
        migrations.AddField(
            model_name="chatbotinteraction",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chatbot_interactions",
                to="courses.course",
            ),
        ),
    ]
